#!/bin/sh

cd src
ghc Main.hs
cd ..

echo "\n"
./src/Main < programs/valid/V1.min
echo "\n"
./src/Main < programs/valid/V2.min
./src/Main < programs/invalid/I1.min
./src/Main < programs/invalid/I2.min
./src/Main < programs/invalid/I3.min
./src/Main < programs/invalid/I4.min
./src/Main < programs/invalid/I5.min
echo "\n"







