#!/bin/sh

echo "\n"
cd src
ghc Main.hs
cd ..

echo "\n"
./src/Main < programs/valid/V1.min
echo "\n"
./src/Main < programs/valid/V2.min
echo "\n"
./src/Main < programs/invalid/I1.min
echo "\n"
./src/Main < programs/invalid/I2.min
echo "\n"
./src/Main < programs/invalid/I3.min
echo "\n"
./src/Main < programs/invalid/I4.min
echo "\n"
./src/Main < programs/invalid/I5.min
echo "\n"







