#!/bin/sh

./make $1

echo "\n"
./run programs/valid/V1.min
echo "\n"
./run programs/valid/V2.min
echo "\n"
./run programs/invalid/I1.min
./run programs/invalid/I2.min
./run programs/invalid/I3.min
./run programs/invalid/I4.min
./run programs/invalid/I5.min
echo "\n"







